name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: nsdmlk
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=bd93f9&color_dots=#44475a,#6272a4,#8be9fd,#ff79c6,#bd93f9,#f8f8f2

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
